### ISSUE TITLE
Add option to change timezone -- for both the adding events and the schedule view

### ISSUE THREAD

**Issue by MichaelZhao21** [MichaelZhao21/tams-club-cal#100]
I would like to have a select menu with the standard [tz database time zones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)

**Comment by The-Box-Lord** [comment]
I think it should just take the current timezone from the system or something (user timezone)

**Comment by MichaelZhao21** [comment]
Yeah by default, it should use the system timezone, but I would like to have a place somewhere to change the timezone if needed. This feature can be added a lot later. Def not a priority issue right now.
