### ISSUE TITLE
Move the name of the event slightly to the right on the schedule view

### ISSUE THREAD

**Issue by MichaelZhao21** [MichaelZhao21/tams-club-cal#130]
## Problem

Currently, on an average desktop view, the schedule view's club name can only fit at most 15 characters (on average). This should be increased so clubs with long names won't seem cramped.

## Proposed Solution

Increase the right margin on the club name or the left margin on the event name.

## Alternative Solution

Limit the number of characters someone can enter in the club name field for events or truncate the name of the club with ellipsis when too long.

**Comment by MichaelZhao21** [comment]
Changes #101 to issue request

**Comment by DylanLi272** [comment]
## Another Solution
Move the club name to the left a bit because there is too much space between the time and club name

**Comment by MichaelZhao21** [comment]
k u do that LOL
