### ISSUE TITLE
Format imports

### ISSUE THREAD

**Issue by MichaelZhao21** [MichaelZhao21/tams-club-cal#137]
## Problem

A lot of the imports in `client/src/pages` are extremely messy and need to be sorted. It is sometimes difficult to find an import. 

## Proposed Solution

I would like for them to be put in the following order (example from `client/src/pages/Resources.js`):

```js
import React from 'react';
import { connect } from 'react-redux';

import LinkBox from '../components/LinkBox';
import Popup from '../components/Popup';
import VolunteeringCard from '../components/VolunteeringCard';
import VolunteeringPopup from '../components/VolunteeringPopup';

import { getVolunteering } from '../functions/api';
import { getSavedVolunteeringList } from '../redux/selectors';
import { setVolunteeringList } from '../redux/actions';

import './Resources.scss';
```

1. Libraries
2. React Components
3. Functions/Redux
4. Scss and other files (like icons)

## Alternate solutions

None

**Comment by Jwright707** [comment]
Hi @MichaelZhao21 I would like to work on this. 👍
