### ISSUE TITLE
Front page not updating when event is edited

### ISSUE THREAD

**Issue by MichaelZhao21** [MichaelZhao21/tams-club-cal#147]
## Bug or Problem

The front page not updated when event is edited until the user goes to a different route and comes back or the page is refreshed.

## Steps to Reproduce

1. Click on one of the events
2. Click the `edit` button at the bottom
3. Change the title of the event, then press `Submit`
4. Exit the popup. 
5. The entry on the menu is not changed :(

## Environment

- System: Arch Linux
- Browser: Firefox, Chrome

## Possible Solution

idk, probably something with updating props on the `client/src/pages/Home.js` page (I'll find a solution)

**Comment by DylanLi272** [comment]
## Another Problem
Same issue when adding events.
Page refresh is required for it to display.
