### ISSUE TITLE
[BUG] After adding Event: Calendar not updated + Invalid key prop

### ISSUE THREAD

**Issue by DylanLi272** [MichaelZhao21/tams-club-cal#163]
### Describe the bug
After adding an event on the Add Event page, the Home page does not update to show the added event.

### To Reproduce
1. Go to 'Add Event' page
2. Add event
3. Go to 'Home' page
4. Look for added event (even though it won't be there)
5. See error

### Expected behavior
Home page should be updated and added event should show up 

### Screenshots or Links
N/A

### Environment
 - OS: Windows
 - Browser: Chrome
 - Browser Version: 87.0.4280.141

### Additional context
N/A

**Comment by MichaelZhao21** [comment]
Current Issues:

- Calendar View is NOT updated
- The added events have an invalid 'key' prop, which makes React unhappy

**Comment by DylanLi272** [comment]
**Fixed:**
> * Calendar View is NOT updated

**Current Issue:**
- The added events have an invalid 'key' prop, which makes React unhappy

Issue is at line 81 of Add.js `this.props.addEvent(newEvent);`
`newEvent` does not have the `objId` property that is generated from the backend
