### ISSUE TITLE
[BUG] Box on button after click

### ISSUE THREAD

**Issue by DylanLi272** [MichaelZhao21/tams-club-cal#166]
### Describe the bug
There is a box after clicking a button

### To Reproduce
1. Go to anywhere with a button
2. Click on the button
3. See error

### Expected behavior
No box should remain after click

### Screenshots or Links
N/A

### Environment
 - OS: Windows
 - Browser: Firefox
 - Browser Version: all versions

### Additional context
N/A

**Comment by MichaelZhao21** [comment]
I thought the

```scss
:focus {
    outline: none;
}
```

fixed it (in `client/src/custom.scss`), but you might need to add the `:active` pseudo tag?

**Comment by DylanLi272** [comment]
Oh it wasn't working on when I tested it but I just tested it again and it worked. Might just be a version issue or something with my setting.
