### ISSUE TITLE
Create Time zone picker

### ISSUE THREAD

**Issue by MichaelZhao21** [MichaelZhao21/tams-club-cal#208]
### Is your feature request related to a problem? Please describe.
Currently time zone is based on your computer time zone, from `dayjs.tz.guess()`. However, there might be cases in which the user would want to change their time zone.

### Describe the solution you'd like
I would like for a simple dropdown menu to change the timezone. The time zones would be one of the standard [tz database time zones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

### Describe alternatives you've considered
N/A

### Additional context
Replacement of #100

**Comment by gbudjeakp** [comment]
Hi Michael,
If say I wanted to work on this issue, would it be okay to use a library like moment to achieve this or is there something more specific you would accept?

**Comment by MichaelZhao21** [comment]
@gbudjeakp I want to avoid using a library for a simple component such as this. I am currently using day.js, which is a lightweight implementation of momentum. I was thinking more along the lines of creating a json file with a list of possible timezones and putting it in a dropdown. Then, the user could just pick from the dropdown, which the default being set to the timezone that is determined by [`dayjs.tz.guess()`](https://day.js.org/docs/en/timezone/guessing-user-timezone).

**Comment by MichaelZhao21** [comment]
There are a lot of timezones in the world, and since this program is only going to be used in America, only the US time zones should be listed -- that means 5 timezones (Hawaiian, Pacific, Mountain, Central, Eastern).

**Comment by gbudjeakp** [comment]
I am currently working on a solution for this. Time can be quite complicated with JavaScript so I'm doing some research first.

**Comment by MichaelZhao21** [comment]
Yeah it definitely doesn't have to be complicated - if you want, just make the dropdown element and I'll connect it with the frontend code we already have.

**Comment by MichaelZhao21** [comment]
not needed anymore
