### ISSUE TITLE
Certain clubs display nothing when clicked

### ISSUE THREAD

**Issue by Jwright707** [MichaelZhao21/tams-club-cal#211]
### Describe the bug
I noticed on the club's page that when clicking on TAMS Culinary Society that nothing appears but the background gets blurry. I'm unsure if this is the intended behavior or not. After digging into the network logs it appears that the BE is throwing a 400 for 3 of the 4 clubs.

### To Reproduce
1. Go to https://tams.club/clubs
2. Click on TAMS Culinary Society (TCS)

### Expected behavior
I would expect some sort of dialog when clicking on one of the clubs.

### Screenshots or Links
![image](https://user-images.githubusercontent.com/40744027/105607555-369fa400-5d54-11eb-973b-60f371e4d1b1.png)
![image](https://user-images.githubusercontent.com/40744027/105607564-428b6600-5d54-11eb-86c8-f6ebf079411f.png)

### Environment
 - OS: Windows
 - Browser: Brave
 - Browser Version: 1.19.86

**Comment by MichaelZhao21** [comment]
Ah yeah that shouldn't be an issue once we clean up the test data. Only the first club has actual data that can be displayed. All of the other clubs are just card placeholders. In the production environment, there should be no clubs that don't have data. We could fix this by closing the popup if no content is found.

**Comment by Jwright707** [comment]
@MichaelZhao21 Sounds good, I'll close the issue. Thank you 👍
