### ISSUE TITLE
[BUG] Error when adding event without opening the main page first

### ISSUE THREAD

**Issue by DylanLi272** [MichaelZhao21/tams-club-cal#221]
### Describe the bug
There is and error message when adding a new event without first loading the main page. The event is added in the backend, but issue is with redux. (See additional context)

### To Reproduce
1. Go to directly to `/add`
2. Add event
3. See error

### Expected behavior
Not have the error and just add event.

### Screenshots or Links
See below 

### Environment
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: N/A

### Additional context
Reason is because `initialState.eventList` is `null` if the main page is not loaded. Fix could be calling `setEventList` from *actions.js* no matter what page the website opens on.

**Comment by DylanLi272** [comment]
![main page not loaded](https://user-images.githubusercontent.com/56173725/105784337-3531cf80-5f3e-11eb-82a6-fa127bbee761.JPG)

**Comment by MichaelZhao21** [comment]
@DylanLi272 uh that probably means eventList is being set to `null` somewhere?

**Comment by MichaelZhao21** [comment]
oh wait cant the initial state just be an empty array
