### ISSUE TITLE
Multiple filters for volunteering

### ISSUE THREAD

**Issue by Jeongwoo55** [MichaelZhao21/tams-club-cal#278]
### Is your feature request related to a problem? Please describe.

Unable to select multiple filters for volunteering opportunities. Ex: Enabling "Open" and "Weekly Signups" filters at the same time does not work.

### Describe the solution you'd like

Add the ability to enable multiple filters at the same time

### Describe alternatives you've considered

N/A

### Additional context

It would be helpful to default to "Open" when loading the page since I doubt many people will want to see closed opportunities.

**Comment by MichaelZhao21** [comment]
Cleaned up old issues
