### ISSUE TITLE
[BUG] Event details cutoff on Mobile

### ISSUE THREAD

**Issue by Jeongwoo55** [MichaelZhao21/tams-club-cal#302]
### Describe the bug

Parts of the event detail text is cutoff on mobile.

### To Reproduce

1. Go to the events page
2. Click on an event with a long description
3. Scroll down to the very bottom

### Expected behavior

I should be able to see the entire event detail text

### Screenshots or Links

![Screenshot_20210320-212258_Firefox](https://user-images.githubusercontent.com/29465791/111891804-9f597480-89c3-11eb-98af-30fddab2fc4f.jpg)

### Environment

 - OS: Android 9
 - Browser: Firefox
 - Browser Version: 86.1.1

also tested on
 - Browser: Samsung Internet
 - Browser Version: 13.2.3.2

### Additional context

N/A

**Comment by MichaelZhao21** [comment]
oh no

**Comment by Jeongwoo55** [comment]
> oh no

oh no indeed. Also, maybe a label for mobile bugs...
