### ISSUE TITLE
Automatically update end time when invalid

### ISSUE THREAD

**Issue by Jeongwoo55** [MichaelZhao21/tams-club-cal#312]
### Is your feature request related to a problem? Please describe.

When updating the starting time, the ending time can become invalid.

### Describe the solution you'd like

When the starting time of an event changes, the ending time should automatically update to be valid (ending time after the starting time). The ending time could be updated by the initial difference between the starting time and the ending time. (Use Google Calendar as reference)

### Describe alternatives you've considered

Copy Google Calendar.

### Additional context

N/A

**Comment by MichaelZhao21** [comment]
Essentially: When user updates start time, preserve the interval between start + end.

**Comment by MichaelZhao21** [comment]
Also note: Change end time only after user *finishes* editing start time/date
