### ISSUE TITLE
[BUG] Event name overlaps middle border

### ISSUE THREAD

**Issue by Jeongwoo55** [MichaelZhao21/tams-club-cal#316]
### Describe the bug

The text in the event overlaps with the line dividing the event name and event description.

### To Reproduce

I'm not sure not exactly sure how to recreate this issue. I assume it occurs when the length of the event name is a specific length so that it was not get moved to the second line.

### Expected behavior

If the word overlaps with the line, the word should be displayed on the second line.

### Screenshots or Links

![Screenshot_2021-03-26_03-27-48](https://user-images.githubusercontent.com/29465791/112603731-4ea3aa80-8e0d-11eb-9a99-f5cb67966d10.png)

### Environment

 - OS: Arch Linux
 - Browser: Chromium
 - Browser Version: 87.0.4280.88

### Additional context

This issue might happen to other pages as well though I could not find any other examples.

**Comment by MichaelZhao21** [comment]
This wasn't pushed to production but should be fixed now. The issue was resolved by #307.
