### ISSUE TITLE
[BUG] Event details only cover half of the screen on mobile

### ISSUE THREAD

**Issue by Jeongwoo55** [MichaelZhao21/tams-club-cal#324]
### Describe the bug

The event detail text only covers half the screen.

### To Reproduce

1. Go to Event page on mobile
2. Click on an event
3. Scroll down to the event details section

### Expected behavior

I expected the event detail text to cover the entire screen.

### Screenshots or Links

![Screenshot_20210331-234852_Firefox](https://user-images.githubusercontent.com/29465791/113245045-c8a7b980-927b-11eb-9486-295a7bca58e8.jpg)

### Environment

 - OS: Android 9
 - Browser: Firefox
 - Browser Version: 87.0.0

### Additional context

N/A

**Comment by MichaelZhao21** [comment]
Forgot to add media query for fix #323 
Assign @MichaelZhao21
