### ISSUE TITLE
[BUG] Disappearing events in Calendar View

### ISSUE THREAD

**Issue by Jeongwoo55** [MichaelZhao21/tams-club-cal#326]
### Describe the bug

Some events do not appear in the Calendar View. After you view a different month, the issue is "fixed". However, the bug does not fix itself when viewing any random month. When viewing March, some events are shown but the events on the first and last weeks of March are missing.

### To Reproduce

1. Go to the Events Page
2. Click on _Show Calendar_
3. See error
4. Click on _<_ and switch to March
5. Click on _>_ and switch to April
6. See error fixed

### Expected behavior

All events should be shown in the Calendar view at any given moment.

### Screenshots or Links

N/A

### Environment

 - OS: Manjaro Linux 21.0
 - Browser: LibreWolf (Firefox)
 - Browser Version: 87.0

### Additional context

This issue is also present on Firefox but only after you change a config.

**Comment by MichaelZhao21** [comment]
Cleaned up old issues
