### ISSUE TITLE
Home Page Feels "Off"

### ISSUE THREAD

**Issue by MichaelZhao21** [MichaelZhao21/tams-club-cal#327]
### Is your feature request related to a problem? Please describe.

Home page hard to "follow" ~ it's hard to tell but there's something off about it

### Describe the solution you'd like

idk

### Describe alternatives you've considered

no

### Additional context

![image](https://user-images.githubusercontent.com/37679458/113554074-5f4ae200-95be-11eb-9fa5-17b998fd2b2d.png)

**Comment by MichaelZhao21** [comment]
Maybe add lines between the events

**Comment by DanielZTing** [comment]
Idk if this has anything to do with it but in my opinion it would improve usability if the event titles were next to the times to make scanning easier (mockup below)

![image](https://user-images.githubusercontent.com/43592069/116013582-8eb9a100-a5f6-11eb-9f77-222bc02c21e4.png)

**Comment by MichaelZhao21** [comment]
I think something that would really help is having 2 rows per item so the club name and time can be stacked underneath or smth. Also text might be too big but def having the event name next to the time is better

**Comment by MichaelZhao21** [comment]
Cleaned up old issues

**Comment by DanielZTing** [comment]
(Just was reminded of this from an email) I wonder if zebra stripes or line divisions would help
