### ISSUE TITLE
[BUG] "Avaliable" spelled wrong on the about page

### ISSUE THREAD

**Issue by MichaelZhao21** [MichaelZhao21/tams-club-cal#459]
### Describe the bug

...This word is spelled wrong on the about page LOL

### To Reproduce

1. Go to https://tams.club/about
2. See the mistake in the FIRST PARAGRAPH

### Expected behavior

Well, it should be spelled right

### Screenshots or Links

![image](https://user-images.githubusercontent.com/37679458/170165561-d4672c12-fb30-40af-90d2-692461106244.png)

### Environment

- OS: Windows 10 (64-bit)
- Browser: Firefox
- Browser Version: 95.0

**Comment by rohit-maheshwari** [comment]
fixed #459

**Comment by MichaelZhao21** [comment]
Fixed by #529
