### ISSUE TITLE
Remove links from data.json

### ISSUE THREAD

**Issue by MichaelZhao21** [MichaelZhao21/tams-club-cal#507]
### Is your feature request related to a problem? Please describe.

Since we changed to saving the links in the database, we no longer need hardcoded external links in the `client/src/data.json` file.

### Describe the solution you'd like

Just remove em'

### Describe alternatives you've considered

N/A

### Additional context

Link to file: https://github.com/MichaelZhao21/tams-club-cal/blob/master/client/src/data.json

**Comment by PrajwalBorkar** [comment]
Please review for changes.
