### ISSUE TITLE
Need to clarify add/edit event "Hide from the public calendar (This will be shown ONLY on the reservation calendar)"

### ISSUE THREAD

**Issue by rohit-maheshwari** [MichaelZhao21/tams-club-cal#509]
### Is your feature request related to a problem? Please describe.
Simply need to clarify to fix user experience related issues

### Describe the solution you'd like
Change it to something that is easier to understand

### Describe alternatives you've considered
Maybe change the label to "Private" so that functionality doesn't need to change

### Additional context
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/61949798/174414807-324560f8-aee5-49e0-9738-9157046a1dd0.png">

**Comment by MichaelZhao21** [comment]
@rohit-maheshwari bump

Here's an idea for what to replace the text with: **Create private event (ONLY show the event on the reservation calendar)**
