### ISSUE TITLE
Volunteering tiles format issue

### ISSUE THREAD

**Issue by The-Box-Lord** [MichaelZhao21/tams-club-cal#69]
1. Tiles move to next line when not suppose to (happens on larger display) [picture here](https://drive.google.com/file/d/1Y-BcS76GEBQikkLbjl3eqgSeTcnR_qPZ/view?usp=sharing)
2. Everything seems to be a little to the left and not quite centered [picture here](https://drive.google.com/file/d/157ZGzyyl5c3VlkxIHxk9IMJ837TpiJaF/view?usp=sharing)

**Comment by MichaelZhao21** [comment]
Should've already been fixed in #74
