### ISSUE TITLE
Club tiles 'overflowing'

### ISSUE THREAD

**Issue by The-Box-Lord** [MichaelZhao21/tams-club-cal#71]
here is a [picture](https://drive.google.com/file/d/1wKd8XkSguTbfJ4dzLJpd9cMNO5LSn0ix/view?usp=sharing) of what i mean

**Comment by MichaelZhao21** [comment]
Can be easily fixed with the `grid-template-columns: repeat(auto-fill, [width]);` css attribute. Check the grid object in `client/src/pages/Resources.scss`

**Comment by MichaelZhao21** [comment]
Check pr #74
