### ISSUE TITLE
Format 404 page

### ISSUE THREAD

**Issue by MichaelZhao21** [MichaelZhao21/tams-club-cal#84]

**Comment by royantar0311** [comment]
hey i have a pr regarding this issue. please check it out  [here](https://github.com/MichaelZhao21/tams-club-cal/pull/124)!

**Comment by MichaelZhao21** [comment]
Still needs more formatting

**Comment by MichaelZhao21** [comment]
I was thinking that this page could say: `The page your are trying to access could not be found :(` at the top and then have a list of links to the other pages. Something like this (but formatted):

# The page you are trying to access could not be found :(
## But here are some cool pages that you could go to:
- Homepage (has the events)
- Resources (with links and volunteering opportunities)
- Clubs (all the clubs at TAMS)
- About (what is this site about and feedback form here)

**Comment by royantar0311** [comment]
I see, im having a look. and will let you know about my progress!

**Comment by royantar0311** [comment]
hey let me know how does it look and if anything more can be done! thanks

![image](https://user-images.githubusercontent.com/31099021/104000786-f4f5f180-51c8-11eb-957f-c1478d5ab753.png)
